name: Test

on:
  workflow_dispatch: {} # allow workflow to be run manually
  push:
    branches: [ main ]

jobs:
  create-cluster:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: terraform.tfstate
          key: terraform.tfstate

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

#     - name: Terraform Init
#       id: init
#       run: terraform init -input=false
# 
#     - name: Terraform Plan
#       id: plan
#       run: terraform plan -input=false
# 
#     - name: Terraform Apply
#       id: apply
#       run: terraform apply -input=false -auto-approve

      - name: Kubectl Config
        run: |
          ls ~/.kube/config
          cat ~/.kube/config
          kubectl get ns

